// Generated by gencpp from file disp_cv/box.msg
// DO NOT EDIT!


#ifndef DISP_CV_MESSAGE_BOX_H
#define DISP_CV_MESSAGE_BOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace disp_cv
{
template <class ContainerAllocator>
struct box_
{
  typedef box_<ContainerAllocator> Type;

  box_()
    : x(0)
    , y(0)
    , h(0)
    , w(0)  {
    }
  box_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , h(0)
    , w(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _h_type;
  _h_type h;

   typedef int32_t _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::disp_cv::box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disp_cv::box_<ContainerAllocator> const> ConstPtr;

}; // struct box_

typedef ::disp_cv::box_<std::allocator<void> > box;

typedef boost::shared_ptr< ::disp_cv::box > boxPtr;
typedef boost::shared_ptr< ::disp_cv::box const> boxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disp_cv::box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disp_cv::box_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace disp_cv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'disp_cv': ['/home/harsh/ros_ws/src/disp_cv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disp_cv::box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7261f46cbfcb221fb85c4d845823bb1b";
  }

  static const char* value(const ::disp_cv::box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7261f46cbfcb221fULL;
  static const uint64_t static_value2 = 0xb85c4d845823bb1bULL;
};

template<class ContainerAllocator>
struct DataType< ::disp_cv::box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disp_cv/box";
  }

  static const char* value(const ::disp_cv::box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disp_cv::box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 h\n\
int32 w\n\
";
  }

  static const char* value(const ::disp_cv::box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disp_cv::box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.h);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disp_cv::box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disp_cv::box_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.h);
    s << indent << "w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISP_CV_MESSAGE_BOX_H
