// Generated by gencpp from file disp_cv/pose.msg
// DO NOT EDIT!


#ifndef DISP_CV_MESSAGE_POSE_H
#define DISP_CV_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace disp_cv
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , r1(0.0)
    , r2(0.0)
    , r3(0.0)  {
    }
  pose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , r1(0.0)
    , r2(0.0)
    , r3(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _r1_type;
  _r1_type r1;

   typedef double _r2_type;
  _r2_type r2;

   typedef double _r3_type;
  _r3_type r3;





  typedef boost::shared_ptr< ::disp_cv::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disp_cv::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::disp_cv::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::disp_cv::pose > posePtr;
typedef boost::shared_ptr< ::disp_cv::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disp_cv::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disp_cv::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace disp_cv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'disp_cv': ['/home/harsh/ros_ws/src/disp_cv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disp_cv::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a916e8e6b6d6e7ed2d34b11e5cf97f25";
  }

  static const char* value(const ::disp_cv::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa916e8e6b6d6e7edULL;
  static const uint64_t static_value2 = 0x2d34b11e5cf97f25ULL;
};

template<class ContainerAllocator>
struct DataType< ::disp_cv::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disp_cv/pose";
  }

  static const char* value(const ::disp_cv::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disp_cv::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 r1\n\
float64 r2\n\
float64 r3\n\
";
  }

  static const char* value(const ::disp_cv::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disp_cv::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.r1);
      stream.next(m.r2);
      stream.next(m.r3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disp_cv::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disp_cv::pose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "r1: ";
    Printer<double>::stream(s, indent + "  ", v.r1);
    s << indent << "r2: ";
    Printer<double>::stream(s, indent + "  ", v.r2);
    s << indent << "r3: ";
    Printer<double>::stream(s, indent + "  ", v.r3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISP_CV_MESSAGE_POSE_H
