// Generated by gencpp from file disp_cv/reg_pos3Dtime.msg
// DO NOT EDIT!


#ifndef DISP_CV_MESSAGE_REG_POS3DTIME_H
#define DISP_CV_MESSAGE_REG_POS3DTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <disp_cv/pos3dtime.h>

namespace disp_cv
{
template <class ContainerAllocator>
struct reg_pos3Dtime_
{
  typedef reg_pos3Dtime_<ContainerAllocator> Type;

  reg_pos3Dtime_()
    : points()
    , ref(0)  {
    }
  reg_pos3Dtime_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , ref(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::disp_cv::pos3dtime_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::disp_cv::pos3dtime_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef int16_t _ref_type;
  _ref_type ref;





  typedef boost::shared_ptr< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> const> ConstPtr;

}; // struct reg_pos3Dtime_

typedef ::disp_cv::reg_pos3Dtime_<std::allocator<void> > reg_pos3Dtime;

typedef boost::shared_ptr< ::disp_cv::reg_pos3Dtime > reg_pos3DtimePtr;
typedef boost::shared_ptr< ::disp_cv::reg_pos3Dtime const> reg_pos3DtimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disp_cv::reg_pos3Dtime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace disp_cv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'disp_cv': ['/home/harsh/ros_ws/src/disp_cv/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e34d86389e60cf5269d611c175e16534";
  }

  static const char* value(const ::disp_cv::reg_pos3Dtime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe34d86389e60cf52ULL;
  static const uint64_t static_value2 = 0x69d611c175e16534ULL;
};

template<class ContainerAllocator>
struct DataType< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disp_cv/reg_pos3Dtime";
  }

  static const char* value(const ::disp_cv::reg_pos3Dtime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pos3dtime[] points\n\
int16 ref\n\
\n\
================================================================================\n\
MSG: disp_cv/pos3dtime\n\
time timestamp\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::disp_cv::reg_pos3Dtime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reg_pos3Dtime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disp_cv::reg_pos3Dtime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disp_cv::reg_pos3Dtime_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::disp_cv::pos3dtime_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "ref: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISP_CV_MESSAGE_REG_POS3DTIME_H
