// Generated by gencpp from file disp-cv/boxes.msg
// DO NOT EDIT!


#ifndef DISP-CV_MESSAGE_BOXES_H
#define DISP-CV_MESSAGE_BOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace disp-cv
{
template <class ContainerAllocator>
struct boxes_
{
  typedef boxes_<ContainerAllocator> Type;

  boxes_()
    : boxes()  {
    }
  boxes_(const ContainerAllocator& _alloc)
    : boxes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::disp-cv::boxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disp-cv::boxes_<ContainerAllocator> const> ConstPtr;

}; // struct boxes_

typedef ::disp-cv::boxes_<std::allocator<void> > boxes;

typedef boost::shared_ptr< ::disp-cv::boxes > boxesPtr;
typedef boost::shared_ptr< ::disp-cv::boxes const> boxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disp-cv::boxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disp-cv::boxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace disp-cv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'disp-cv': ['/home/harsh/ros_ws/src/disp-cv/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::disp-cv::boxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disp-cv::boxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp-cv::boxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disp-cv::boxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp-cv::boxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disp-cv::boxes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disp-cv::boxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e8557e2ff1ec2810133dc2374d362e1";
  }

  static const char* value(const ::disp-cv::boxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e8557e2ff1ec281ULL;
  static const uint64_t static_value2 = 0x0133dc2374d362e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::disp-cv::boxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disp-cv/boxes";
  }

  static const char* value(const ::disp-cv::boxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disp-cv::boxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] boxes\n\
";
  }

  static const char* value(const ::disp-cv::boxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disp-cv::boxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct boxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disp-cv::boxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disp-cv::boxes_<ContainerAllocator>& v)
  {
    s << indent << "boxes[]" << std::endl;
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      s << indent << "  boxes[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.boxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISP-CV_MESSAGE_BOXES_H
